# zsh - compsys
autoload -U compinit; compinit
zstyle ':completion:*:default' menu true select

# zsh - alias
alias ls='ls -FG'

# zsh - history
HISTFILE=$ZDOTDIR/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt extended_history
setopt share_history
setopt inc_append_history
setopt hist_ignore_space
setopt hist_no_store

# sheldon
eval "$(sheldon source)"
## sheldon - pure
autoload -U promptinit; promptinit
prompt pure

# mise
eval "$(/Users/tsuu32/.local/bin/mise activate zsh)"