# zsh - compsys
autoload -U compinit; compinit
zstyle ':completion:*:default' menu true select

# zsh - alias
alias ls='ls -FG'

# zsh - history
HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
HISTSIZE=1000000
SAVEHIST=1000000
setopt extended_history
setopt share_history
setopt inc_append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_no_store

# sheldon
if command -v sheldon >/dev/null 2>&1; then
	eval "$(sheldon source)"
    # pure
    autoload -U promptinit; promptinit
    prompt pure
fi

# mise
if [ -x "$HOME/.local/bin/mise" ]; then
	eval "$($HOME/.local/bin/mise activate zsh)"
fi

# Moddable SDK
if [ -d "$HOME/work/Moddable-OpenSource/moddable" ]; then
	export MODDABLE="$HOME/work/Moddable-OpenSource/moddable"
	export PATH="${MODDABLE}/build/bin/mac/release:$PATH"
fi

# ESP-IDF
if [ -d "$HOME/esp/esp-idf" ]; then
	alias get_idf='. $HOME/esp/esp-idf/export.sh'
fi

# swiftly
. "$HOME/.swiftly/env.sh"